### ISSUE TITLE
Data split fails

### ISSUE THREAD

**Issue by yonatansverdlov** [AvivNavon/deep-align#2]
Hi I have two issues:
First, I run python experiments/utils/data/generate_splits.py --data-root datasets/mnist_classifiers --save-path datasets/splits.json to create the splits and have the following error:    raise ValueError(
ValueError: With n_samples=0, test_size=0.25 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
Second, can you add the networks of all other datasets like CIFAR10, LST?
Thanks!

**Comment by AvivNavon** [comment]
Hi, could you please make sure that the `all_files` list (here: https://github.com/AvivNavon/deep-align/blob/main/experiments/utils/data/generate_splits.py#L16) is not empty?

**Comment by yonatansverdlov** [comment]
It's empty but I followed the instructions.

**Comment by AvivNavon** [comment]
Could you please provide the structure of the `datasets/mnist_classifiers` folder?

**Comment by yonatansverdlov** [comment]
it contains around 10K models.

**Comment by AvivNavon** [comment]
But what is the structure of the `datasets/mnist_classifiers` folder? Are there other folders inside? Or just the `*.pth` files (e.g., `datasets/mnist_classifiers/model_xx.pth`)

**Comment by AvivNavon** [comment]
Are you sure you pass the correct path as `--data-root`?
Try this please:
```python
from pathlib import Path
data_root = "datasets/mnist_models"
data_root = Path(data_root)
all_files = [p.as_posix() for p in data_root.glob("**/*.pth")]
all_files[:10]
```

The output should look like this:
```
['datasets/mnist_models/model_899.pth', 'datasets/mnist_models/model_3082.pth', 'datasets/mnist_models/model_641.pth', 'datasets/mnist_models/model_4935.pth', 'datasets/mnist_models/model_1695.pth', 'datasets/mnist_models/model_7582.pth', 'datasets/mnist_models/model_6844.pth', 'datasets/mnist_models/model_8869.pth', 'datasets/mnist_models/model_5395.pth', 'datasets/mnist_models/model_127.pth']
```

**Comment by yonatansverdlov** [comment]
Thanks, I'll check it out.
I ran python experiments/utils/data/generate_splits.py --data-root
datasets/mnist_classifiers --save-path datasets/splits.json without change.
Should I have done any changes inside the command?

‫בתאריך יום ה׳, 11 ביולי 2024 ב-0:16 מאת ‪Aviv Navon‬‏ <‪
***@***.***‬‏>:‬

**Comment by AvivNavon** [comment]
Try providing a full path to `datasets/mnist_classifiers` (and not relative).

**Comment by yonatansverdlov** [comment]
['datasets/mnist_models/model_3302.pth', 'datasets/mnist_models/model_2930.pth', 'datasets/mnist_models/model_2542.pth', 'datasets/mnist_models/model_1457.pth', 'datasets/mnist_models/model_1825.pth', 'datasets/mnist_models/model_4309.pth', 'datasets/mnist_models/model_5549.pth', 'datasets/mnist_models/model_9289.pth', 'datasets/mnist_models/model_2123.pth', 'datasets/mnist_models/model_2684.pth']
Full path yeilds the same.

**Comment by AvivNavon** [comment]
Try running the generate_splits.py command with full path (and maybe provide test/val sizes)

**Comment by yonatansverdlov** [comment]
tried but fails

‫בתאריך יום ה׳, 11 ביולי 2024 ב-0:28 מאת ‪Aviv Navon‬‏ <‪
***@***.***‬‏>:‬

**Comment by yonatansverdlov** [comment]
I tried running what you asked explicitly and got all_files = [ ]. Although
as I showed before, there are paths.

‫בתאריך יום ה׳, 11 ביולי 2024 ב-0:30 מאת יונתן סברדלוב <‪
***@***.***‬‏>:‬

**Comment by AvivNavon** [comment]
Could you share the exact command you are using and the full trace?
Also, could you please try to debug to understand why the file structure does not fit `data_root.glob("**/*.pth")` ?

**Comment by yonatansverdlov** [comment]
Regarding commands:
mkdir datasets
wget "https://www.dropbox.com/s/sv85hrjswaspok4/mnist_classifiers.zip"
unzip -q mnist_classifiers.zip -d datasets
python experiments/utils/data/generate_splits.py --data-root
datasets/mnist_classifiers --save-path datasets/splits.json

‫בתאריך יום ה׳, 11 ביולי 2024 ב-9:43 מאת ‪Aviv Navon‬‏ <‪
***@***.***‬‏>:‬

**Comment by AvivNavon** [comment]
I think I see the problem, the subfolder is called `mnist_models` and not `mnist_classifiers `

**Comment by yonatansverdlov** [comment]
Ok so what is the fix?

‫בתאריך יום ה׳, 11 ביולי 2024 ב-9:53 מאת ‪Aviv Navon‬‏ <‪
***@***.***‬‏>:‬

**Comment by AvivNavon** [comment]
```bash

python experiments/utils/data/generate_splits.py --data-root datasets/mnist_classifiers --save-path datasets/splits.json
```

**Comment by AvivNavon** [comment]
Also, I suggest providing exact sizes for the test/val splits using `--test-size` and `--val-size`

**Comment by yonatansverdlov** [comment]
Worked but inside generate.py  what val/test splited you took in the paper?

‫בתאריך יום ה׳, 11 ביולי 2024 ב-9:59 מאת ‪Aviv Navon‬‏ <‪
***@***.***‬‏>:‬

**Comment by AvivNavon** [comment]
I believe we provide the full experimental details in the Appendix of the paper

**Comment by yonatansverdlov** [comment]
And what about other datasets?

‫בתאריך יום ה׳, 11 ביולי 2024 ב-10:07 מאת יונתן סברדלוב <‪
***@***.***‬‏>:‬

**Comment by AvivNavon** [comment]
We will make the effort to release other datasets and the supporting code in the future

**Comment by AvivNavon** [comment]
We've released the code for the CNNs experiments

**Comment by yonatansverdlov** [comment]
Awesome, thanks for the update!
Does it include also CIFAR exps?

**Comment by AvivNavon** [comment]
Yes.
